project:
  type: website
  output-dir: _site
  resources:
    - "/docs/download/_download.json"
    - "/docs/download/_prerelease.json"
    - "/_redirects"
    - CNAME


website:
  title: "Ghassem Tofighi"
  image: "images/dark-back.jpg"
  favicon: "images/favicon.svg"
  google-analytics: "G-aaaaa"
  open-graph: true
  twitter-card: true
  #site-path: "/courses/"
  site-url: https://tofighi.github.io/courses
  repo-url: https://github.com/tofighi/courses
  issue-url: https://github.com/tofighi/courses/issues/new/choose
  repo-actions: [edit]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
    
  page-footer:
    left: |
      Proudly supported by
      [![](https://sinamedialab.com/assets/img/logo@2x-black.png){fig-alt="Sina Media Lab" width=65px}](https://sinamedialab.com)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
    right:
      - icon: twitter
        href: https://twitter.com/tofighi
        aria-label: Twitter
      - icon: github
        href: https://github.com/tofighi/
        aria-label: GitHub       
  navbar:
    background: light
    logo: images/logo.svg
    logo-alt: "Ghassem Tofighi's logo."
    title: false
    collapse-below: lg
    left:
      - text: "About"
        href: about.qmd
      - text: "Assignments"
        href: docs/assignments/index.qmd
      - text: "Ask a Question"
        href: https://askdatascience.com
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/tofighi/web2/issues"
          - text: "Request a Feature"
            icon: "lightbulb"
            href: "#"

    tools:
      - icon: twitter
        href: https://x.com/tofighi
        text: X
      - icon: github
        href: https://github.com/tofighi
        text: GitHub 


bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


filters:
  - filters/tools-tabset.lua


freeze: true

editor: visual

profile:
  group: 
    - [prerelease,rc]
