blank_issues_enabled: true
contact_links:
  - name: Open an issue about Quarto
    url: https://github.com/quarto-dev/quarto-cli/issues/new/choose
    about: For any issue or unexpected behavior with Quarto, please go to the main repo
  - name: Ask a question about Quarto
    url: https://github.com/quarto-dev/quarto-cli/discussions/categories/q-a
    about: Please ask and answer questions in our main Discussion board
  - name: Share an idea, a missing feature or anything else
    url: https://github.com/quarto-dev/quarto-cli/discussions/
    about: Please give us any feedback in our main Discussion board
