blank_issues_enabled: true
contact_links:
  - name: Open an issue about courses website
    url: https://github.com/tofighi/courses/issues/new/choose
    about: For any issue or unexpected behavior with courses website
  - name: Share an idea, a missing feature, or anything else
    url: https://github.com/tofighi/courses/discussions/
    about: Please give us any feedback on the main Discussion board
