# This file applies only to the 'docs/deep-learning' section
project:
  type: website
  output-dir: ../../_site/docs/deep-learning

website:
  title: "Deep Learning"
  page-navigation: true
  search: true

sidebar: true  # Enable sidebar only for this section

sidebar:
  - id: deep-learning
    collapse-level: 3
    contents:
      - section: "Deep Learning"
        href: index.qmd
        contents:
          - section: Part 1
            contents:
              - lesson1.qmd
              - lesson2.qmd
              - lesson3.qmd
              - lesson4.qmd
              - lesson5.qmd
              - lesson6.qmd
              - lesson7.qmd
              - lesson8.qmd
              - lesson8a.qmd
              - section: Summaries
                contents:
                  - Summaries/lesson1.qmd
                  - Summaries/lesson2.qmd
                  - Summaries/lesson3.qmd
                  - Summaries/lesson4.qmd
                  - Summaries/lesson5.qmd
                  - Summaries/lesson6.qmd
                  - Summaries/lesson7.qmd
                  - Summaries/lesson8.qmd
          - text: "---"
          - section: Part 2
            contents:
              - part2.qmd
              - lesson9.qmd
              - lesson10.qmd
              - lesson11.qmd
              - lesson12.qmd
              - lesson13.qmd
              - lesson14.qmd
              - lesson15.qmd
              - lesson16.qmd
              - lesson17.qmd
              - lesson18.qmd
              - lesson19.qmd
              - lesson20.qmd
              - lesson21.qmd
              - lesson22.qmd
              - lesson23.qmd
              - lesson24.qmd
              - lesson25.qmd
              - text: "Bonus: Lesson 9a"
                href: https://youtu.be/0_BBRNYInx8
              - text: "Bonus: Lesson 9b"
                href: https://youtu.be/mYpjmM7O-30
          - text: "---"
          - section: Resources
            contents:
              - Resources/book.qmd
              - Resources/forums.qmd
              - Resources/kaggle.qmd
              - Resources/testimonials.qmd

format:
  html:
    toc: true
    sidebar: true  # Sidebar enabled for the deep-learning section
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: ../../styles.css
    include-before-body: |
      <!-- Link to Google Fonts -->
      <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Raleway:wght@400;700&display=swap" rel="stylesheet">
      <style>
        /* Apply Lato font to headers (h1, h2, h3, etc.) */
        h1, h2, h3, h4, h5, h6 {
          font-family: 'Lato', sans-serif;
        }
        
        /* Apply Raleway font to body text */
        body {
          font-family: 'Raleway', sans-serif;
        }
      </style>
