on:
  pull_request:
    branches: [main, v1.4]
  issue_comment:
    types: [created]

name: Deploy Preview

jobs:
  is-external-pr:
    # Be helpful with reviewer and remind them to trigger a deploy preview if the PR is from a fork.
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Error with message for manual deploy
        run: |
          echo "::error title=Manual action required for preview::PR from fork can't be deployed as preview to Netlify automatically. Use '/deploy-preview' command in comments to trigger the preview manually."
        shell: bash

  build-deploy-preview:
    # Deploy a preview only if 
    # - the PR is not from a fork,
    # - requested by PR comment /deploy-preview
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork != true) || 
      (github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER' || github.event.comment.author_association == 'COLLABORATOR') && startsWith(github.event.comment.body, '/deploy-preview')) 
      
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with: 
          ref: refs/pull/${{ github.event.pull_request.number || github.event.issue.number }}/merge

      - name: Get latest pre-release from github
        id: github-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo version=$(gh api repos/quarto-dev/quarto-cli/releases | jq -r 'map(select(.prerelease)) | first | .tag_name | sub("^v";"")') >> "$GITHUB_OUTPUT"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ steps.github-release.outputs.version }}

      - name: Render 
        uses: quarto-dev/quarto-actions/render@v2
        with: 
          to: html

      - name: Deploy Preview to Netlify as preview
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v2
        env:
          NETLIFY_SITE_ID: 2a3da659-672b-4e5b-8785-e10ebf79a962
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          publish-dir: './_site'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: |
            Deploy from GHA: ${{ github.event.pull_request.title || format('manual from PR {0}', github.event.issue.number) }}
          alias: deploy-preview-${{ github.event.pull_request.number || github.event.issue.number }}
          # these all default to 'true'
          enable-pull-request-comment: true
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
        timeout-minutes: 1
