# Regenerates the download json
name: Update Downloads
on:
  workflow_dispatch:
  schedule:
    - cron:  "*/15 * * * *"
jobs:
  update-downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMIT_PAT }}
      - name: Regenerate Download Json
        uses: ./.github/workflows/actions/release-info
        with:
          owner: 'quarto-dev'
          repo: 'quarto-cli'
          out-path: 'docs/download/'
          redirects-path: '_redirects'
          redirects-template: /download/latest/$$prefix$$-$$suffix$$.$$extension$$
          pre-redirects-template: /download/prerelease/$$prefix$$-$$suffix$$.$$extension$$
          github-token: ${{ github.token }}
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          commit_user_name: Github Action Runner
          commit_user_email: runner@quarto.org
          skip_checkout: true
