# Uploads index to our Algolia Index
name: Upload Index
on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  upload-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6        
      - name: Install Algolia API Dependencies
        run: |
          gem install algolia
      - name: Upload Index
        run: |
          pwd
          ruby .github/workflows/upload-algolia.rb
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: ZPJB5I1QN7
          ALGOLIA_INDEX: prod_QUARTO
          QUARTO_INDEX_PATH: search.json
          
          
